### ISSUE TITLE
SyntaxError: Unexpected token in serve.js command

### ISSUE THREAD

**Issue by jhagege** [jenkins-docs/building-a-multibranch-pipeline-project#10]
Hi, I've been following the tutorial.
When doing the command `./node_modules/serve/bin/serve.js -c 0 -s build &` inside `deploy-for-production.sh`, I get the error:

```
const updateCheck = async (isDebugging) => {
                          ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
```

Any idea how to fix ? 
Thanks !

**Comment by MarkEWaite** [comment]
Fixed in most recent commit by switching to the latest NodeJS and updating the launch script
